# Generated by Django 2.1.2 on 2018-12-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_auto_20181210_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='telefone',
            field=models.CharField(max_length=100),
        ),
    ]
