# Generated by Django 2.1.2 on 2018-12-10 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0008_auto_20181210_2201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dataregistro',
            new_name='registro',
        ),
    ]
