# Generated by Django 2.1.2 on 2018-12-10 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0011_auto_20181210_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataregistro',
            name='tel',
        ),
    ]
